# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - debuggedlabs

on:
  push:
    branches:
      - master

jobs:

  # build job
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run deploy
    
  # deployment job
  - job: deploy
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: build
    condition: succeeded()
    
    steps:
      # publish the build artifact
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: drop

      # download the artifact
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: drop

      # deploy the app
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'debuggedlabs-site'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_75053c3ebac04dedb22c8deaacb53d4e }}
          package: drop