# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - debuggedlabs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run deploy

    # publish the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    # download generated artifact
    - name: Download artiifact
      uses: actions/download-artifact@v1
      with:
        name: dist

      # deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'debuggedlabs-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_75053c3ebac04dedb22c8deaacb53d4e }}
        package: dist