# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: DebuggedLabs Deployment Cycle

env:
  AZURE_WEBAPP_NAME: 'debuggedlabs-site'
  AZURE_WEBAPP_PACKAGE_PATH: '.'          

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.14'

    - name: npm install, build, and test
      run: |
        cd debuggedlabs-site
        npm install
        npm run build --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f6ef5893d3ee41cfa79494eaed30e481 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}